### ISSUE TITLE
Angular4 ng new - Unexpected value 'MoneyMaskModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by ahelord** [rodolfocop/ng2-mask-money#19]
In a new proyect angular cli 1.0.4 import module and get error

Uncaught Error: Unexpected value 'MoneyMaskModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:56360:34)
    at http://localhost:4200/vendor.bundle.js:70044:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:70027:49)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:81350:70)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:81323:36)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:81252:37)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:5627:25)
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:5613:21)
    at Object.125 (http://localhost:4200/main.bundle.js:19:124)

**Comment by rodolfocop** [comment]
Hello, should I have more details on how you are using a directive?

**Comment by thackerronak** [comment]
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/node_modules/ng2-money-mask/node_modules/@angular/core/core.d.ts, resolving symbol MoneyMaskModule in /Users/node_modules/ng2-money-mask/src/mask/money-mask.module.ts, resolving symbol MoneyMaskModule in /Users/node_modules/ng2-money-mask/src/mask/money-mask.module.ts

**Comment by rodolfocop** [comment]
Hi, I'm closing this issue. 
Please, this error keeps, open new questions.
