### ISSUE TITLE
Doesn't work with Angular 5 targeting es5

### ISSUE THREAD

**Issue by Hainesy** [rodolfocop/ng2-mask-money#27]
WARNING in ./node_modules/ng2-money-mask/node_modules/@angular/core/@angular/core.es5.js
5905:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\...\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\...\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\...\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\...\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\...\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\...\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\...\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ng2-money-mask/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng2-money-mask/src/mask/money-mask.directive.ts
 @ ./node_modules/ng2-money-mask/src/mask/index.ts
 @ ./node_modules/ng2-money-mask/index.ts
 @ ./src/app/test/test.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by rodolfocop** [comment]
Hi, we will update soon. 
Wait a few more days.
Thanks

**Comment by rodolfocop** [comment]
Hi, try to use this new version #28

**Comment by rodolfocop** [comment]
Hi, I am closing these issues if the problem still persists again.
