### ISSUE TITLE
Error on start app

### ISSUE THREAD

**Issue by ctelles-cwi** [rodolfocop/ng2-mask-money#32]
ERROR in ./node_modules/ng2-money-mask/index.ts
Module build failed: Error: C:\Users\carlos.telles\workspace\estudos\snackBarAdmin\node_modules\ng2-money-mask\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Pa
ckage Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\carlos.telles\workspace\estudos\snackBarAdmin\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\carlos.telles\workspace\estudos\snackBarAdmin\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by rodolfocop** [comment]
Hi, Which version are you using?

**Comment by rodolfocop** [comment]
I'll be closing this issue, if you still have problems just open a new one.
